---
apiVersion: v1
kind: Namespace
metadata:
  name: rbac-sample
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-account
  namespace: rbac-sample
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-role
  namespace: rbac-sample
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
